spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scraper-db
      auto-index-creation: true

accounts-import:
  scheduler:
    number-of-threads: 10
    timeout-minutes: 2
    shutdown-timeout-seconds: 10

logging:
  level:
    org.apache.http:
      wire: DEBUG
