spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scraper-db

service:
  session-header: x-session

accounts-import:
  scheduler:
    number-of-threads: 10
    timeout-minutes: 2
    shutdown-timeout-seconds: 10
  retention-hours: 24
